version = 0.1
[default.deploy.parameters]
stack_name = "note-app"
resolve_s3 = true
s3_prefix = "note-app"
region = "ap-southeast-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
